[package]
name = "futures-example"
version = "0.1.0"
edition = "2018"
# edition = "2021"

[dependencies]
rand = "0.7.2"
futures = "0.3.1"
futures-timer = "2.0.2"

[dependencies.async-std]
version = "1.2.0"
features = ["unstable"]
